name: CI
on:
  push: 
    branches:
    - master
jobs:
  regressions:
    name: Build & Deploy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: "Install yarn"
        run: "npm i -g yarn"
      - name: "Cache node modules"
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: "Cache yarn"
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: "Build and Deploy"
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@master
        env:
          BRANCH: gh-pages
          ACCESS_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          FOLDER: build
          BUILD_SCRIPT: 'yarn && yarn build'

